import { StyleSheet } from 'react-native';

export const AuthColors = {
    primary: '#00A6CA',
    primaryDark: '#008FB0',
    background: '#FFFFFF',
    lightBackground: '#F5F5F5',
    border: '#E0E0E0',
    text: '#333333',
    textLight: '#666666',
    textPlaceholder: '#999999',
    white: '#FFFFFF',
    success: '#4CAF50',
    error: '#F44336',
    genderSelected: '#00A6CA',
    genderUnselected: '#E0E0E0',
};

export const AuthStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: AuthColors.background,
    },
    scrollView: {
        flexGrow: 1,
    },
    headerImage: {
        width: '100%',
        height: 300,
        resizeMode: 'cover',
    },
    logoContainer: {
        position: 'absolute',
        top: 40,
        right: 20,
        zIndex: 10,
    },
    logoText: {
        fontSize: 24,
        fontWeight: 'bold',
        color: AuthColors.primary,
    },
    formContainer: {
        backgroundColor: AuthColors.white,
        borderTopLeftRadius: 30,
        borderTopRightRadius: 30,
        marginTop: -30,
        paddingHorizontal: 24,
        paddingTop: 32,
        paddingBottom: 40,
        minHeight: '100%',
    },
    title: {
        fontSize: 24,
        fontWeight: 'bold',
        color: AuthColors.primary,
        textAlign: 'center',
        marginBottom: 8,
    },
    subtitle: {
        fontSize: 14,
        color: AuthColors.textLight,
        textAlign: 'center',
        marginBottom: 24,
    },
    inputLabel: {
        fontSize: 14,
        color: AuthColors.text,
        marginBottom: 8,
        fontWeight: '500',
    },
    inputContainer: {
        marginBottom: 20,
    },
    input: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: AuthColors.border,
        borderRadius: 8,
        paddingHorizontal: 12,
        paddingVertical: 14,
        backgroundColor: AuthColors.white,
    },
    inputIcon: {
        marginRight: 10,
    },
    inputText: {
        flex: 1,
        fontSize: 16,
        color: AuthColors.text,
    },
    phonePrefix: {
        fontSize: 16,
        color: AuthColors.text,
        marginRight: 8,
    },
    hintText: {
        fontSize: 12,
        color: AuthColors.textLight,
        marginTop: 4,
        lineHeight: 16,
    },
    errorText: {
        fontSize: 12,
        color: AuthColors.error,
        marginTop: 4,
        lineHeight: 16,
    },
    splitInputWrapper: {
        flexDirection: 'row',
        gap: 12,
    },
    prefixContainer: {
        width: 80,
        height: 50,
        borderWidth: 1,
        borderColor: AuthColors.border,
        borderRadius: 8,
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: AuthColors.white,
    },
    mainInputContainer: {
        flex: 1,
        height: 50,
        borderWidth: 1,
        borderColor: AuthColors.border,
        borderRadius: 8,
        paddingHorizontal: 16,
        justifyContent: 'center',
        backgroundColor: AuthColors.white,
    },
    inputSplit: {
        fontSize: 16,
        color: AuthColors.text,
        height: '100%',
    },
    primaryButton: {
        backgroundColor: AuthColors.primary,
        borderRadius: 8,
        paddingVertical: 16,
        alignItems: 'center',
        marginTop: 24,
    },
    primaryButtonText: {
        color: AuthColors.white,
        fontSize: 16,
        fontWeight: 'bold',
    },
    dividerContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginVertical: 24,
    },
    dividerLine: {
        flex: 1,
        height: 1,
        backgroundColor: AuthColors.border,
    },
    dividerText: {
        marginHorizontal: 16,
        fontSize: 14,
        color: AuthColors.textLight,
    },
    socialButton: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: AuthColors.border,
        borderRadius: 8,
        paddingVertical: 12,
        marginBottom: 12,
        backgroundColor: AuthColors.white,
    },
    socialButtonIcon: {
        marginRight: 12,
    },
    socialButtonText: {
        fontSize: 16,
        color: AuthColors.text,
        fontWeight: '500',
    },
    socialButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 16,
        marginBottom: 24,
    },
    socialButtonIconOnly: {
        flex: 1,
        height: 50,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: AuthColors.border,
        borderRadius: 12,
        backgroundColor: AuthColors.white,
    },
    linkContainer: {
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        marginTop: 16,
    },
    linkText: {
        fontSize: 14,
        color: AuthColors.textLight,
    },
    linkTextBold: {
        fontSize: 14,
        color: AuthColors.primary,
        fontWeight: 'bold',
    },
    termsContainer: {
        marginTop: 16,
        alignItems: 'center',
    },
    termsText: {
        fontSize: 12,
        color: AuthColors.textLight,
        textAlign: 'center',
    },
    termsLink: {
        fontSize: 12,
        color: AuthColors.primary,
        fontWeight: '500',
    },
    genderContainer: {
        marginBottom: 20,
    },
    genderButtonGroup: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 8,
    },
    genderButton: {
        flex: 1,
        paddingVertical: 12,
        borderRadius: 8,
        borderWidth: 1,
        alignItems: 'center',
    },
    genderButtonSelected: {
        backgroundColor: AuthColors.primary,
        borderColor: AuthColors.primary,
    },
    genderButtonUnselected: {
        backgroundColor: AuthColors.white,
        borderColor: AuthColors.border,
    },
    genderButtonTextSelected: {
        color: AuthColors.white,
        fontSize: 16,
        fontWeight: '500',
    },
    genderButtonTextUnselected: {
        color: AuthColors.text,
        fontSize: 16,
    },
});
